import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from '@vercel/analytics/react';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CombusTank",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" data-theme="corporate">
        <body className={inter.className}>
          <Navbar />
          <main>{children}</main>
          <Footer />
          <Analytics />
        </body>
      </html>
  );
}
